BEGIN;
--
-- Create model Destination
--
CREATE TABLE "pagoumorou_destination" ("id" uuid NOT NULL PRIMARY KEY, "destination_id" integer NOT NULL UNIQUE, "name" varchar(255) NOT NULL, "country_id" varchar(2) NOT NULL, "destination_type" varchar(2) NOT NULL, "parent_destination_id" integer NULL, "image_url" varchar(200) NULL);
--
-- Create model Feature
--
CREATE TABLE "pagoumorou_feature" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(100) NOT NULL);
--
-- Create model User
--
CREATE TABLE "pagoumorou_user" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "birth_date" date NOT NULL, "gender" varchar(10) NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "password" varchar(128) NOT NULL, "role" varchar(10) NOT NULL);
--
-- Create model Property
--
CREATE TABLE "pagoumorou_property" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "type" varchar(20) NOT NULL, "rules" text NOT NULL, "address" text NOT NULL, "destination_id" uuid NOT NULL);
--
-- Create model Room
--
CREATE TABLE "pagoumorou_room" ("id" uuid NOT NULL PRIMARY KEY, "room_number" varchar(50) NOT NULL, "capacity" integer NOT NULL, "shared" boolean NOT NULL, "weekly_price" numeric(10, 2) NOT NULL, "biweekly_price" numeric(10, 2) NOT NULL, "monthly_price" numeric(10, 2) NOT NULL, "property_id" uuid NOT NULL);
--
-- Create model Proposal
--
CREATE TABLE "pagoumorou_proposal" ("id" uuid NOT NULL PRIMARY KEY, "proposed_price" numeric(10, 2) NOT NULL, "period" varchar(10) NOT NULL, "move_in_date" date NOT NULL, "move_out_date" date NOT NULL, "message" text NOT NULL, "status" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "room_id" uuid NOT NULL, "reviewed_by_id" uuid NULL, "user_id" uuid NOT NULL);
--
-- Create model RoomFeature
--
CREATE TABLE "pagoumorou_roomfeature" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "feature_id" uuid NOT NULL, "room_id" uuid NOT NULL);
--
-- Create model RoomPhoto
--
CREATE TABLE "pagoumorou_roomphoto" ("id" uuid NOT NULL PRIMARY KEY, "url" varchar(200) NOT NULL, "room_id" uuid NOT NULL);
--
-- Create model PropertyManager
--
CREATE TABLE "pagoumorou_propertymanager" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "property_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model Location
--
CREATE TABLE "pagoumorou_location" ("id" uuid NOT NULL PRIMARY KEY, "start_date" date NOT NULL, "end_date" date NOT NULL, "created_at" timestamp with time zone NOT NULL, "proposal_id" uuid NOT NULL UNIQUE, "room_id" uuid NOT NULL, "user_id" uuid NOT NULL);
CREATE INDEX "pagoumorou_user_email_950b31ef_like" ON "pagoumorou_user" ("email" varchar_pattern_ops);
ALTER TABLE "pagoumorou_property" ADD CONSTRAINT "pagoumorou_property_destination_id_933906c5_fk_pagoumoro" FOREIGN KEY ("destination_id") REFERENCES "pagoumorou_destination" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "pagoumorou_property_destination_id_933906c5" ON "pagoumorou_property" ("destination_id");
ALTER TABLE "pagoumorou_room" ADD CONSTRAINT "pagoumorou_room_property_id_2319e68d_fk_pagoumorou_property_id" FOREIGN KEY ("property_id") REFERENCES "pagoumorou_property" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "pagoumorou_room_property_id_2319e68d" ON "pagoumorou_room" ("property_id");
ALTER TABLE "pagoumorou_proposal" ADD CONSTRAINT "pagoumorou_proposal_room_id_541c2e80_fk_pagoumorou_room_id" FOREIGN KEY ("room_id") REFERENCES "pagoumorou_room" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "pagoumorou_proposal" ADD CONSTRAINT "pagoumorou_proposal_reviewed_by_id_84783e5f_fk_pagoumoro" FOREIGN KEY ("reviewed_by_id") REFERENCES "pagoumorou_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "pagoumorou_proposal" ADD CONSTRAINT "pagoumorou_proposal_user_id_187f87a8_fk_pagoumorou_user_id" FOREIGN KEY ("user_id") REFERENCES "pagoumorou_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "pagoumorou_proposal_room_id_541c2e80" ON "pagoumorou_proposal" ("room_id");
CREATE INDEX "pagoumorou_proposal_reviewed_by_id_84783e5f" ON "pagoumorou_proposal" ("reviewed_by_id");
CREATE INDEX "pagoumorou_proposal_user_id_187f87a8" ON "pagoumorou_proposal" ("user_id");
ALTER TABLE "pagoumorou_roomfeature" ADD CONSTRAINT "pagoumorou_roomfeatu_feature_id_50118847_fk_pagoumoro" FOREIGN KEY ("feature_id") REFERENCES "pagoumorou_feature" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "pagoumorou_roomfeature" ADD CONSTRAINT "pagoumorou_roomfeature_room_id_620fd384_fk_pagoumorou_room_id" FOREIGN KEY ("room_id") REFERENCES "pagoumorou_room" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "pagoumorou_roomfeature_feature_id_50118847" ON "pagoumorou_roomfeature" ("feature_id");
CREATE INDEX "pagoumorou_roomfeature_room_id_620fd384" ON "pagoumorou_roomfeature" ("room_id");
ALTER TABLE "pagoumorou_roomphoto" ADD CONSTRAINT "pagoumorou_roomphoto_room_id_7e1c731d_fk_pagoumorou_room_id" FOREIGN KEY ("room_id") REFERENCES "pagoumorou_room" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "pagoumorou_roomphoto_room_id_7e1c731d" ON "pagoumorou_roomphoto" ("room_id");
ALTER TABLE "pagoumorou_propertymanager" ADD CONSTRAINT "pagoumorou_propertym_property_id_8616d10e_fk_pagoumoro" FOREIGN KEY ("property_id") REFERENCES "pagoumorou_property" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "pagoumorou_propertymanager" ADD CONSTRAINT "pagoumorou_propertym_user_id_5b7eaedb_fk_pagoumoro" FOREIGN KEY ("user_id") REFERENCES "pagoumorou_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "pagoumorou_propertymanager_property_id_8616d10e" ON "pagoumorou_propertymanager" ("property_id");
CREATE INDEX "pagoumorou_propertymanager_user_id_5b7eaedb" ON "pagoumorou_propertymanager" ("user_id");
ALTER TABLE "pagoumorou_location" ADD CONSTRAINT "pagoumorou_location_proposal_id_7e94b990_fk_pagoumoro" FOREIGN KEY ("proposal_id") REFERENCES "pagoumorou_proposal" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "pagoumorou_location" ADD CONSTRAINT "pagoumorou_location_room_id_db073d94_fk_pagoumorou_room_id" FOREIGN KEY ("room_id") REFERENCES "pagoumorou_room" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "pagoumorou_location" ADD CONSTRAINT "pagoumorou_location_user_id_537e5872_fk_pagoumorou_user_id" FOREIGN KEY ("user_id") REFERENCES "pagoumorou_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "pagoumorou_location_room_id_db073d94" ON "pagoumorou_location" ("room_id");
CREATE INDEX "pagoumorou_location_user_id_537e5872" ON "pagoumorou_location" ("user_id");
COMMIT;
