# Generated by Django 5.2.1 on 2025-06-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoumorou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='biweekly_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='weekly_price',
        ),
        migrations.AddField(
            model_name='room',
            name='accept_men',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='accept_women',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Week', 'Week'), ('Biweek', 'Biweek'), ('Month', 'Month'), ('Semester', 'Semester'), ('Year', 'Year')], default='Semester', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagoumorou.room')),
            ],
        ),
    ]
