# Generated by Django 5.2.1 on 2025-06-21 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoumorou', '0003_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 0, 0)),
        ),
        migrations.AddField(
            model_name='room',
            name='available_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
