# Generated by Django 5.2.1 on 2025-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoumorou', '0004_property_description_room_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
