# Generated by Django 5.2.1 on 2025-06-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoumorou', '0005_room_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destination_type',
            field=models.CharField(choices=[('CT', 'Country'), ('ST', 'State'), ('CI', 'City'), ('NB', 'Neighborhood'), ('PL', 'Place')], max_length=2),
        ),
    ]
